// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcvpthzbairrmnktrhaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjdnB0aHpiYWlycm1ua3RyaGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTMyMzUsImV4cCI6MjA1Nzc2OTIzNX0.TXcajT4ahbssQ2EMbpyG87nQ6HtLqkXuMxDTAKcLSZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);